### PR TITLE
Fix scotch build issue (#22)

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Review by charest — APPROVED** [review]
So the only reason legion depends on scotch is because they both install a file "common.h"?

**Comment by junghans** [comment]
Kind of, legion installs a `common.h` which scotch picks up and then fails to build.

**Comment by junghans** [comment]
Also I am not sure why it picks up legion's `common.h` in the first place, the include dir seems to be correct:
https://github.com/junghans/scotch/blob/cmake/src/libscotch/CMakeLists.txt#L293

**Comment by charest** [comment]
I understand now....

In scotch.cmake, one of the CMAKE_ARGS is 

    -DZLIB_INCLUDE_DIR:PATH=${ZLIB_INCLUDE_DIR}

and in zlib.cmake it is set to the install prefix...

    set(ZLIB_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)

**Comment by junghans** [comment]
Good catch, could we make it point to ${CMAKE_BINARY_DIR}/zlib/.../include` instead?

**Comment by charest** [comment]
We could do something like

    ExternalProject_Get_Property(${ZLIB_NAME} source_dir)
    set(ZLIB_INCLUDE_DIR ${source_dir})

But there is also zconf.h which is cmake_configure'd in the binary dir so I'm not sure.  The includes are not all in the same place.  Your way might be better?

**Comment by junghans** [comment]
Let's do another pull-request and fix the include path instead.

**Comment by junghans** [comment]
Replaced by #24.

**Pull request closed without merging**
