### PR TITLE
Added this stable branch to deployment

### PR DESCRIPTION
**Pull request by ktsai7**

### CODE REVIEW

**Review by junghans — APPROVED** [review]

**Comment by ktsai7** [comment]
Does this make travis only build master and stables?

**Comment by junghans** [comment]
Yes, we had that in flesci already, but not flecsi-third-party.

**Comment by ktsai7** [comment]
Right, I remember that. Remind me... so all the other branches only gets travis build if it's in a PR?

**Comment by junghans** [comment]
Correct!

**Pull request merged**
