### PR TITLE
Dockerfile: enabling flecsi tests

### PR DESCRIPTION
**Pull request by junghans**
HPX (version 931402c) fails to build on Fedora 30 with following error:
```
-- Performing Test HPX_WITH_CXX11_ATOMIC - Failed
-- Test failed, detailed output:

Change Dir: /home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_98b7f/fast 
gmake[3]: Entering directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTC_98b7f.dir/build.make CMakeFiles/cmTC_98b7f.dir/build
gmake[4]: Entering directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o
/usr/lib64/ccache/c++   -I/home/flecsi/tpl/hpx  -DENABLE_LEGION_TLS  -std=c++17   -o CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o -c /home/flecsi/tpl/hpx/cmake/tests/cxx11_std_atomic.cpp
Linking CXX executable cmTC_98b7f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_98b7f.dir/link.txt --verbose=1
/usr/lib64/ccache/c++   -DENABLE_LEGION_TLS  -std=c++17    -rdynamic CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o  -o cmTC_98b7f  -L/home/flecsi/tpl/build/hpx/src/hpx-build/lib 
/usr/bin/ld: CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o: in function `std::atomic<uint128_type>::store(uint128_type, std::memory_order)':
cxx11_std_atomic.cpp:(.text._ZNSt6atomicI12uint128_typeE5storeES0_St12memory_order[_ZNSt6atomicI12uint128_typeE5storeES0_St12memory_order]+0x62): undefined reference to `__atomic_store_16'
/usr/bin/ld: CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o: in function `std::atomic<uint128_type>::load(std::memory_order) const':
cxx11_std_atomic.cpp:(.text._ZNKSt6atomicI12uint128_typeE4loadESt12memory_order[_ZNKSt6atomicI12uint128_typeE4loadESt12memory_order]+0x2d): undefined reference to `__atomic_load_16'
collect2: error: ld returned 1 exit status
gmake[4]: *** [CMakeFiles/cmTC_98b7f.dir/build.make:87: cmTC_98b7f] Error 1
gmake[4]: Leaving directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'
gmake[3]: *** [Makefile:121: cmTC_98b7f/fast] Error 2
gmake[3]: Leaving directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'

[91mCMake Error at cmake/HPX_Message.cmake:47 (message):
  HPX needs support for C++11 std::atomic
Call Stack (most recent call first):
  cmake/HPX_AddConfigTest.cmake:137 (hpx_error)
  cmake/HPX_AddConfigTest.cmake:411 (add_hpx_config_test)
  cmake/HPX_PerformCxxFeatureTests.cmake:92 (hpx_check_for_cxx11_std_atomic)
  CMakeLists.txt:1174 (hpx_perform_cxx_feature_tests)


[0m-- Configuring incomplete, errors occurred!
```

So disabling it for now.

@ipdemes if you know a version that works on Fedora 30, just bump the submodule and revert this PR.

/cc @hkaiser @sithhell

### CODE REVIEW

**Review by ktsai7 — APPROVED** [review]

**Comment by junghans** [comment]
I think @tuxfan did the same fix another branch, but I could find it.

**Comment by ktsai7** [comment]
It would be nice to see the output of this build just with hpx disable

**Comment by junghans** [comment]
Some flecsi tests fail:
```
The following tests FAILED:
[91mErrors while running CTest
[0m	  1 - dcrs (Failed)
	  2 - boxcolor2d (Failed)
	  3 - boxcolor3d (Failed)
	  8 - future_handle (Failed)
	  9 - handle_list (Failed)
	 10 - data_handle_task (Failed)
	 11 - handle_accessor (Failed)
	 12 - ghost_access (Failed)
	 14 - data_client_handle (Failed)
	 15 - dense_data (Failed)
	 16 - finite_difference_dense (Failed)
	 17 - global_data (Failed)
	 18 - sparse_data (Failed)
	 19 - finite_difference_sparse (Failed)
	 20 - ragged_data (Failed)
	 21 - internal_task (Failed)
	 23 - serdez (Failed)
	 24 - read_waits_on_write (Failed)
[91mmake: *** [Makefile:62: test] Error 8
```

**Comment by ktsai7** [comment]
Is this related to openmpi vs mpich?

**Comment by hkaiser** [comment]
@junghans we're working on a solution, not sure yet what's wrong.

**Comment by ktsai7** [comment]
After updating the container to use fedora:rawhide to get openmpi 4, flecsi's tests are passing again on fedora.
Going to revert the disable of HPX and see if it is also fixed.

**Comment by sithhell** [comment]
That's very strange, as far as I am aware, our fedora packages for the 1.3.0 release (a943fd2) are working fine on fedora f30:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1298822
(build log for x86: https://kojipkgs.fedoraproject.org//packages/hpx/1.3.0/2.fc31/data/logs/x86_64/build.log not seeing anything surprising there...)

Was this error introduced only after that? I think having a fixed commit that works for you is always a save, bumping the version every now and then is always a good idea though.

**Comment by junghans** [comment]
> That's very strange, as far as I am aware, our fedora packages for the 1.3.0 release (a943fd2) are working fine on fedora f30:
> https://koji.fedoraproject.org/koji/buildinfo?buildID=1298822
> (build log for x86: https://kojipkgs.fedoraproject.org//packages/hpx/1.3.0/2.fc31/data/logs/x86_64/build.log not seeing anything surprising there...)
> 
> Was this error introduced only after that? I think having a fixed commit that works for you is always a save, bumping the version every now and then is always a good idea though.

Your links are all for f31, not f30, f30 only builds hpx-1.2.1, see:
https://apps.fedoraproject.org/packages/hpx

and we don't use `-DHPX_IGNORE_COMPILER_COMPATIBILITY=ON -DHPX_WITH_BUILD_BINARY_PACKAGE=ON` nor `-DHPX_WITH_BUILD_BINARY_PACKAGE=ON`, which might disable some checks.

**Pull request merged**
