### PR TITLE
Enable HPX

### PR DESCRIPTION
**Pull request by ktsai7**
HPX (version 931402c) fails to build on Fedora 30 with following error:
```
-- Performing Test HPX_WITH_CXX11_ATOMIC - Failed
-- Test failed, detailed output:

Change Dir: /home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_98b7f/fast 
gmake[3]: Entering directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTC_98b7f.dir/build.make CMakeFiles/cmTC_98b7f.dir/build
gmake[4]: Entering directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o
/usr/lib64/ccache/c++   -I/home/flecsi/tpl/hpx  -DENABLE_LEGION_TLS  -std=c++17   -o CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o -c /home/flecsi/tpl/hpx/cmake/tests/cxx11_std_atomic.cpp
Linking CXX executable cmTC_98b7f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_98b7f.dir/link.txt --verbose=1
/usr/lib64/ccache/c++   -DENABLE_LEGION_TLS  -std=c++17    -rdynamic CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o  -o cmTC_98b7f  -L/home/flecsi/tpl/build/hpx/src/hpx-build/lib 
/usr/bin/ld: CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o: in function `std::atomic<uint128_type>::store(uint128_type, std::memory_order)':
cxx11_std_atomic.cpp:(.text._ZNSt6atomicI12uint128_typeE5storeES0_St12memory_order[_ZNSt6atomicI12uint128_typeE5storeES0_St12memory_order]+0x62): undefined reference to `__atomic_store_16'
/usr/bin/ld: CMakeFiles/cmTC_98b7f.dir/cxx11_std_atomic.cpp.o: in function `std::atomic<uint128_type>::load(std::memory_order) const':
cxx11_std_atomic.cpp:(.text._ZNKSt6atomicI12uint128_typeE4loadESt12memory_order[_ZNKSt6atomicI12uint128_typeE4loadESt12memory_order]+0x2d): undefined reference to `__atomic_load_16'
collect2: error: ld returned 1 exit status
gmake[4]: *** [CMakeFiles/cmTC_98b7f.dir/build.make:87: cmTC_98b7f] Error 1
gmake[4]: Leaving directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'
gmake[3]: *** [Makefile:121: cmTC_98b7f/fast] Error 2
gmake[3]: Leaving directory '/home/flecsi/tpl/build/hpx/src/hpx-build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp'

�[91mCMake Error at cmake/HPX_Message.cmake:47 (message):
  HPX needs support for C++11 std::atomic
Call Stack (most recent call first):
  cmake/HPX_AddConfigTest.cmake:137 (hpx_error)
  cmake/HPX_AddConfigTest.cmake:411 (add_hpx_config_test)
  cmake/HPX_PerformCxxFeatureTests.cmake:92 (hpx_check_for_cxx11_std_atomic)
  CMakeLists.txt:1174 (hpx_perform_cxx_feature_tests)


�[0m-- Configuring incomplete, errors occurred!
So disabling it for now.
```
@ipdemes if you know a version that works on Fedora 30, just bump the submodule in this PR and merge this PR.

/cc @hkaiser @sithhell

### CODE REVIEW

**Comment by hkaiser** [comment]
@ktsai7 yes, that's exactly what we see as well. It's still a miracle, however. @rtohid is working on providing a solution as we speak.

**Comment by sithhell** [comment]
Something that would help is to set the cmake variable HPX_HAVE_LIBATOMIC as a workaround. Something is off with the detection for that...

**Comment by hkaiser** [comment]
The problem seems to be that `-latomic` on that platform does not support 16byte atomics. We might want to separate the feature test for those as only one of the schedulers depends on it anyways...

**Comment by hkaiser** [comment]
@ktsai7 would you have a chance to verify whether https://github.com/STEllAR-GROUP/hpx/pull/3996 fixes the issue you reported?

**Comment by hkaiser** [comment]
@ktsai7 FWIW, STEllAR-GROUP/hpx#3996 has been merged now. Thanks for helping to fix this issue.

**Comment by ipdemes** [comment]
@junghans : could you, please,review this?

**Review by junghans — APPROVED** [review]

**Pull request merged**
