### PR TITLE
Fix installation directory of HPX library.

### PR DESCRIPTION
**Pull request by rtohid**
If HPX is installed, the installation directory is passed- instead of the build directory.

### CODE REVIEW

**Comment by ipdemes** [comment]
@rtohid : I think I understand why you have created this pull request, but I don't think we need the proposed changes. Since few weeks ago some temporary "install" directory was added to the build path. This was made in purpose to have "make Install" call work correctly. So when someone type make all the libraries will be installed into the teporary build/install. And then when they push "make install" the files from the temporary "install" directory would be copied to the specified prefix path. So I assume you are missing "make install" call when you build you third-party-libraries.

**Comment by rtohid** [comment]
Thank you @ipdemes . As I remember, I did `make install` and everything was being installed in the installation directory I'd set. I'll look into this in more details and let you know.

**Comment by ipdemes** [comment]
@rtohid :could you, please, check that?

**Comment by ipdemes** [comment]
Seems fine to mee. @rtohid : could you, please, check this on your system?

Irina

**Comment by ipdemes** [comment]
@rtohid @junghans : this seems to work for me so I am merging this branch to the master

**Comment by rtohid** [comment]
Thank you @ipdemes .

**Pull request merged**
