### PR TITLE
Updating legion submodule

### PR DESCRIPTION
**Pull request by ipdemes**

### CODE REVIEW

**Comment by ipdemes** [comment]
@junghans : could you, please, hard-merge this pull request? I will merge my legion_master branch into flecsi then (this should fix broken builds)

**Comment by junghans** [comment]
@ipdemes , just merge `legion_master` first!

**Comment by ipdemes** [comment]
@junghans just did so. How do I restart travis checks here?

**Comment by junghans** [comment]
I already did ;-)

**Review by junghans — APPROVED** [review]

**Comment by junghans** [comment]
@ipdemes: There is still something broken in `FindLegion.cmake`.

**Comment by ipdemes** [comment]
@junghans OK. I am looking into that

**Pull request merged**
