### PR TITLE
Enabling C++ for HDF5

### PR DESCRIPTION
**Pull request by ipdemes**
@junghans @tuxfan Is there a reason why we want C++ being disabled fro HDF5?
this change was suggested by @dmringo

### CODE REVIEW

**Comment by korobkin** [comment]
I believe C++ doesn't work with parallel HDF5. It's either one or the other, and it hasn't been fixed even in the most recent version of HDF5:

    install/hdf5-1.10.3$ ./configure --enable-cxx --enable-parallel
    <... skipped ...>
    configure: error: --enable-cxx and --enable-parallel flags are incompatible. Use --enable-unsupported to override this error.

**Comment by dmringo** [comment]
Neither the C++ nor parallel features are enabled by default in the external project build currently.  Is there a way of telling CMake to propagate command line options to the external build to enable either of these features, or would that have to be manually set up?

It would be nice to be able to override the flag(s) in `hdf5.cmake` with something like

```sh
cmake path/to/flecsi-tpl -DHDF5_BUILD_CPP_LIB=ON
```

Aside: Is the idea that there should be one "true" build of third party libraries that any FleCSI-based projects can use, or is customization (e.g. with the HDF5 C++ API) accepted/encouraged.

**Comment by junghans** [comment]
@dmringo you know to that handing in the varables through, i.e. run cmake in hdf5.cmake with the option `-DHDF5_BUILD_CPP_LIB=${HDF5_BUILD_CPP_LIB}`.

**Comment by zetwal** [comment]
I talked to Ben some time back about Parallel HDF5 and C++, and he is happy using the C bindings of HDF5.

I was talking to some HDF5 people about this and the current state of C++ and parallel HDF5 is:
"Enabling C++ and HDF5 parallel is something we are not tackling in the ECP project. AFAIK, it is more of a resource issue at The HDF Group (THG) to develop this. There have been attempts to wrap C functions within C++. If you are already doing that, please try --enable-cxx and --enable-parallel together with --enable-unsupported to see if the CMake errors go away. " - Suren Brya

The latest I heard on this is that the HDF5 folks know that there is growing interest in that and they were going to have a telecon to talk about this.

**Comment by dmringo** [comment]
@junghans Yes, I was just hoping CMake might have some sort of special support for recursive CMake via `externalproject_add` that would inherit the parent's specified options.  It would be tedious to rewrite all, or even some non-trivial subset of a sub-project's options if you want to expose them in the build.

**Comment by junghans** [comment]
Hmm, I don’t know of any other way...the idea of external projects in CMake is to build them in very controlled environment, so automatically inheriting stuff would be orthogonal of that!

**Comment by dmringo** [comment]
That's a good point.  I guess having explicit variables in the parent project is a better idea here.

**Pull request closed without merging**
