### PR TITLE
Fix our legion config to build against our hdf5

### PR DESCRIPTION
**Pull request by cferenba**
This modifies the configuration for legion to correctly find our hdf5 build (if requested).

@ktsai7 @ipdemes : please review.  @opensdh : FYI.

### CODE REVIEW

**Comment by cferenba** [comment]
As I suspected, something has changed in the environment in the past few months, such that the HEAD of master passed CI on Aug 9, but doesn't pass now (see #89 and #91).

What to do?

**Comment by cmsquared** [comment]
Is this one of the repos whose CI has been moved to gitlab?

**Comment by cferenba** [comment]
> Is this one of the repo's whose CI has been moved to gitlab?

I looked on gitlab and didn't see it.  But even if it's there, there's no reason why this CI shouldn't pass.

**Comment by cmsquared** [comment]
Ok.  I didn't know if something had changed to accommodate gitlab that was incompatible with travis.

**Comment by cferenba** [comment]
Good suggestion, but I don't think that's the issue.

**Comment by ktsai7** [comment]
@cferenba retry?

**Comment by cferenba** [comment]
@ktsai7 : looks like the build reran and passed, thanks!

@ktsai7 @ipdemes @tuxfan : would one of you please review and merge?

**Comment by ipdemes** [comment]
@cferenba :did you have to do this changes because of some kind of issues with the FindHDF5 from cmake?

**Comment by cferenba** [comment]
@ipdemes : yes, the FindHDF5 from cmake wasn't behaving as expected.

**Comment by ipdemes** [comment]
@cferenba I see, I have had some similar experience myself. Looks good to me.

**Review by ipdemes — APPROVED** [review]

**Pull request merged**
